#! /usr/bin/env python3
# generated by ChatGPT Codex
import argparse
import re
from pathlib import Path

parser = argparse.ArgumentParser()
parser.add_argument("input", nargs="?", type=Path, default=Path("strip.xml"))
parser.add_argument("output", nargs="?", type=Path, default=Path("strip-output.csv"))
parser.add_argument("--keep-br", action="store_true")

ROW_PATTERN = re.compile(
    r"<Cell>(?P<text1>.*?)</Cell><Cell>(?P<text2>.*?)</Cell><Cell>(?P<text3>.*?)</Cell>",
    re.DOTALL,
)


def csv_field(value: str) -> str:
    escaped = value.replace('"', '""')
    return f'"{escaped}"'


def html_escape_for_text(value: str) -> str:
    return value.replace('"', "&quot;").replace("<", "&lt;").replace(">", "&gt;")


def normalize_text3(value: str, keep_br: bool) -> str:
    if not keep_br:
        value = value.replace("&lt;br/&gt;", "  ")

    replacements = (
        ("“", "「"),
        ("”", "」"),
        ("？", "?"),
        ("！", "!"),
        ("（", " ("),
        ("）", ") "),
        ("［", " ["),
        ("］", "] "),
        ("｛", " {"),
        ("｝", "} "),
        ("：", ":"),
        ("；", ";"),
        ("，", ","),
        ("．", "."),
    )
    for source, target in replacements:
        value = value.replace(source, target)
    return value


def read_rows(text: str) -> list[tuple[str, str, str]]:
    text = text.replace("<Table>", "").replace("</Table>", "")

    starts = [match.start() for match in re.finditer(r"<Row>", text)]
    if not starts:
        raise ValueError("no <Row> entries were found in the input file")

    rows: list[tuple[str, str, str]] = []
    for index, start in enumerate(starts):
        end = starts[index + 1] if index + 1 < len(starts) else len(text)
        block = text[start:end].rstrip()
        if not block.endswith("</Row>"):
            block += "</Row>"

        match = ROW_PATTERN.search(block)
        if match is None:
            raise ValueError(f"invalid row block: {block!r}")

        rows.append((match.group("text1"), match.group("text2"), match.group("text3")))
    return rows


def main(args: argparse.Namespace) -> None:
    source = args.input.read_text(encoding="utf-8")
    rows = read_rows(source)

    with args.output.open("w", encoding="utf-8", newline="") as handle:
        for row_id, text2, text3 in rows:
            text3_normalized = normalize_text3(text3, args.keep_br)
            text3_normalized = html_escape_for_text(text3_normalized)

            handle.write(
                ",".join(
                    [
                        csv_field(row_id),
                        csv_field(html_escape_for_text(text2)),
                        csv_field(""),
                        csv_field(text3),
                        csv_field(text3_normalized),
                        "1",
                    ]
                )
                + "\n"
            )


if __name__ == "__main__":
    main(parser.parse_args())
